/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppMylistRouteImport } from './routes/_app/mylist'
import { Route as AppBrowseIndexRouteImport } from './routes/_app/browse/index'
import { Route as AppTitleIdRouteImport } from './routes/_app/title/$id'
import { Route as AppBrowseSeriesRouteImport } from './routes/_app/browse/series'
import { Route as AppBrowseNewRouteImport } from './routes/_app/browse/new'
import { Route as AppBrowseMoviesRouteImport } from './routes/_app/browse/movies'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppMylistRoute = AppMylistRouteImport.update({
  id: '/mylist',
  path: '/mylist',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseIndexRoute = AppBrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => AppRoute,
} as any)
const AppTitleIdRoute = AppTitleIdRouteImport.update({
  id: '/title/$id',
  path: '/title/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseSeriesRoute = AppBrowseSeriesRouteImport.update({
  id: '/browse/series',
  path: '/browse/series',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseNewRoute = AppBrowseNewRouteImport.update({
  id: '/browse/new',
  path: '/browse/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseMoviesRoute = AppBrowseMoviesRouteImport.update({
  id: '/browse/movies',
  path: '/browse/movies',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/mylist': typeof AppMylistRoute
  '/search': typeof AppSearchRoute
  '/browse/movies': typeof AppBrowseMoviesRoute
  '/browse/new': typeof AppBrowseNewRoute
  '/browse/series': typeof AppBrowseSeriesRoute
  '/title/$id': typeof AppTitleIdRoute
  '/browse/': typeof AppBrowseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/mylist': typeof AppMylistRoute
  '/search': typeof AppSearchRoute
  '/browse/movies': typeof AppBrowseMoviesRoute
  '/browse/new': typeof AppBrowseNewRoute
  '/browse/series': typeof AppBrowseSeriesRoute
  '/title/$id': typeof AppTitleIdRoute
  '/browse': typeof AppBrowseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/mylist': typeof AppMylistRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/browse/movies': typeof AppBrowseMoviesRoute
  '/_app/browse/new': typeof AppBrowseNewRoute
  '/_app/browse/series': typeof AppBrowseSeriesRoute
  '/_app/title/$id': typeof AppTitleIdRoute
  '/_app/browse/': typeof AppBrowseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/mylist'
    | '/search'
    | '/browse/movies'
    | '/browse/new'
    | '/browse/series'
    | '/title/$id'
    | '/browse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/mylist'
    | '/search'
    | '/browse/movies'
    | '/browse/new'
    | '/browse/series'
    | '/title/$id'
    | '/browse'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/mylist'
    | '/_app/search'
    | '/_app/browse/movies'
    | '/_app/browse/new'
    | '/_app/browse/series'
    | '/_app/title/$id'
    | '/_app/browse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mylist': {
      id: '/_app/mylist'
      path: '/mylist'
      fullPath: '/mylist'
      preLoaderRoute: typeof AppMylistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/': {
      id: '/_app/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof AppBrowseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/title/$id': {
      id: '/_app/title/$id'
      path: '/title/$id'
      fullPath: '/title/$id'
      preLoaderRoute: typeof AppTitleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/series': {
      id: '/_app/browse/series'
      path: '/browse/series'
      fullPath: '/browse/series'
      preLoaderRoute: typeof AppBrowseSeriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/new': {
      id: '/_app/browse/new'
      path: '/browse/new'
      fullPath: '/browse/new'
      preLoaderRoute: typeof AppBrowseNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/movies': {
      id: '/_app/browse/movies'
      path: '/browse/movies'
      fullPath: '/browse/movies'
      preLoaderRoute: typeof AppBrowseMoviesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMylistRoute: typeof AppMylistRoute
  AppSearchRoute: typeof AppSearchRoute
  AppBrowseMoviesRoute: typeof AppBrowseMoviesRoute
  AppBrowseNewRoute: typeof AppBrowseNewRoute
  AppBrowseSeriesRoute: typeof AppBrowseSeriesRoute
  AppTitleIdRoute: typeof AppTitleIdRoute
  AppBrowseIndexRoute: typeof AppBrowseIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMylistRoute: AppMylistRoute,
  AppSearchRoute: AppSearchRoute,
  AppBrowseMoviesRoute: AppBrowseMoviesRoute,
  AppBrowseNewRoute: AppBrowseNewRoute,
  AppBrowseSeriesRoute: AppBrowseSeriesRoute,
  AppTitleIdRoute: AppTitleIdRoute,
  AppBrowseIndexRoute: AppBrowseIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
